join-message: false
leave-message: false
spawn-join: true

spawn:
  world: world
  x: 120
  y: 120
  z: 120
  yaw: 16.0
  pitch: 90.0

npcs:
  test:
    id: 1
    name: test
    texture: ewogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJpZCIgOiAiZDIzZDcxNzIxMTZmNDkxNDgxZDViMzVhYzRkZmRkZWEiLAogICAgICAidHlwZSIgOiAiU0tJTiIsCiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNjNmNGQ1NTVmYjNiOTM1N2FmNzU4MmYyNzM4MDBmMWRhNGFjNjliMDQyMTBjM2FhMzRlNjNkYjJhNDIzNWJiZiIsCiAgICAgICJwcm9maWxlSWQiIDogIjBiMzFiZmZmYTMwZDQ3OGJiMDllZWZjOTEyOWI4MGE4IiwKICAgICAgInRleHR1cmVJZCIgOiAiNjNmNGQ1NTVmYjNiOTM1N2FmNzU4MmYyNzM4MDBmMWRhNGFjNjliMDQyMTBjM2FhMzRlNjNkYjJhNDIzNWJiZiIKICAgIH0KICB9LAogICJza2luIiA6IHsKICAgICJpZCIgOiAiZDIzZDcxNzIxMTZmNDkxNDgxZDViMzVhYzRkZmRkZWEiLAogICAgInR5cGUiIDogIlNLSU4iLAogICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS82M2Y0ZDU1NWZiM2I5MzU3YWY3NTgyZjI3MzgwMGYxZGE0YWM2OWIwNDIxMGMzYWEzNGU2M2RiMmE0MjM1YmJmIiwKICAgICJwcm9maWxlSWQiIDogIjBiMzFiZmZmYTMwZDQ3OGJiMDllZWZjOTEyOWI4MGE4IiwKICAgICJ0ZXh0dXJlSWQiIDogIjYzZjRkNTU1ZmIzYjkzNTdhZjc1ODJmMjczODAwZjFkYTRhYzY5YjA0MjEwYzNhYTM0ZTYzZGIyYTQyMzViYmYiCiAgfSwKICAiY2FwZSIgOiBudWxsCn0=
    signature: ppWWd9zMCWwBA4mg/Kf8CjmOOYVCFTJZMGO+FUNKp0mrO22DN8sRftNICM8FtDh3HqpUJK9a9yO73J06bfBxhfHMszdxzD6Sqk0ZH4eXIXLcy5YKlPTmanka8UmNrRVOroArqabPVYrsTUgIVtxnxRRTVMjnIyiP57K+H8XB3IVwKMqKk2M/83wXE3P58pfvmIiAmbth0yLlUWryR/xQsV2jP1jahTVqjXIlDbZV7RoqZMzB6Gz5nGN+zP6/rEPPpfyowdcs2lsqQ37mDOHzWggCcsG7tSYFMPCiSpkiTVDb2LQWke42ODjFisqKuqM0mzEIkXP9IrRMBmEIPiV+IIfwiV4elgzfevIhg9eMeL8dQe/3t2ay7S4y/IFxuJhULJAp7r4trFv4LFYq1ixRgt49xmVfRFbnl5W5+6JyKjswRBJ+FNpmzxK3iYtJj1/k4MLrk4UIYLtmhSLwJoKJAm4u2TXXmGmbWZjA+qeESqewY3Vr4sLigiwhmAF83BjoT7UFYFANDZs6YZCwUA5iUTs34gL4BrRqp00h6lnhKl2RbkWXw1d4IeFbtcdP1OG51pq0v65g0jPDNfxLvlCHEwIxvxuWrE9wegwtXGvXLYOBnYWqe9Xsuwk8PEvzXxG3l81+wcFc0oHdpAfzp5+YN7UXbdb4zim8ENOvbWH+Td4=
    uuid: 62ce816c-7a9d-11ea-bc55-0242ac130003
    interact:
      type: GUI
      info: servers
    location:
      world: world
      x: 40
      y: 80
      z: 85
      yaw: 0.0
      pitch: 0.0
