main: papertools.main.Papertools
name: Papertools
author: wouter173
version: 2.1
api-version: 1.13
commands:
  papertools:
    usage: /<command> [reload]
    description: papertools command
  npc:
    usage: /<command> [list|create|delete]
    description: link into papertools npc api

permissions:
  papertools.*:
    description: all papertools permissions
    default: op
    children:

      papertools.command.*:
        description: all papertools commands permissions
        default: op
        children:

          papertools.command.papertools:
            description: papertools command permission for reload and version
            default: op

          papertools.command.npc:
            description: papertools command permission for npc
            default: op

